# -*- coding: utf-8 -*-

# @File  : save_profile.py
# @Author: zibang
# @Time  : 2月 27,2022
# @Desc
import json

data = {'acceptLanguage': 'sv-FI,sv;q=0.9',
        'appName': 'Netscape',
        'audio': {'noise': True},
        'browserApi': {'accuracy': '1803.34',
                       'autoGeoIp': True,
                       'batteryPercentage': '1',
                       'chargingTime': '0',
                       'default': [],
                       'drainsTime': 'Infinity',
                       'isCharging': True,
                       'lang': [],
                       'latitude': '51.482594',
                       'localService': [],
                       'longitude': '-0.007661',
                       'name': [],
                       'setAccuracy': False,
                       'setBatteryStatus': False,
                       'setBluetoothAdapter': False,
                       'setLatitude': False,
                       'setLongitude': False,
                       'setWebBluetooth': False,
                       'speechSynthesis': False,
                       'voiceURI': []},
        'browserParams': '',
        'browserSettings': {'audioMute': False,
                            'disablePdf': False,
                            'disableWebSecurity': False,
                            'fakeUiForMedia': True,
                            'gpuAndPepper3D': False,
                            'hyperlinkAuditing': True,
                            'ignoreCertErrors': False,
                            'mediaStream': True,
                            'pepperFlash': False,
                            'touchEvents': False,
                            'webkitSpeech': True},
        'canvasDefType': 'NOISE',
        'clientRects': True,
        'cmdcfg': {'closeCommandLine': True,
                   'commandLine': '',
                   'openCommandLine': False},
        'customDns': '',
        'deviceMemory': 8,
        'deviceType': 0,
        'doNotTrack': False,
        'dynamicFonts': True,
        'fontList': [],
        'fontSetting': {'clientRects': True, 'dynamicFonts': True, 'fontList': []},
        'hardwareConcurrency': 8,
        'header': {'list': {'enable': [],
                            'name': [],
                            'notExistAdd': [],
                            'urlMatch': [],
                            'value': []},
                   'setHeaderCustom': False},
        'hideWebdriver': False,
        'iconId': 0,
        'kernelVer': '96',
        'langBasedOnIp': True,
        'langHdr': 'sv-FI',
        'leakProof': {'computerName': 'DESKTOP-6SN1NNT',
                      'macAddress': 'B4-6B-FC-0A-05-04'},
        'localCache': {'clearCache': False,
                       'clearHistory': False,
                       'deleteCache': False,
                       'deleteCookie': False},
        'maskFonts': True,
        'mediaDevices': {'audioInputs': 0,
                         'audioOutputs': 2,
                         'list': {'audioInputs': [],
                                  'audioOutputs': [],
                                  'videoInputs': []},
                         'setMediaDevices': True,
                         'use_name': False,
                         'videoInputs': 1},
        'mobileEmulation': False,
        'name': '500( 18)',
        'notes': '',
        'os': 'Linux',
        'otherProtection': {'localPortsExclude': '', 'setPortScan': True},
        'pixelRatio': '1.0',
        'platform': 'Android',
        'pluginFingerprint': {'list': {'describe': [],
                                       'fileName': [],
                                       'mimeDescription': [],
                                       'mimeExtension': [],
                                       'mimeType': [],
                                       'name': []},
                              'pluginEnable': False},
        'product': 'Gecko',
        'proxyHost': '',
        'proxyPass': '',
        'proxyPort': '',
        'proxyServer': {'host': '',
                        'password': '',
                        'port': '',
                        'setProxyServer': False,
                        'type': 'HTTP',
                        'username': ''},
        'proxyType': 'HTTP',
        'proxyUser': '',
        'remoteDebug': {'bindAllDebug': False, 'debuggingPort': 0, 'logLevels': 99},
        'screenHeight': 640,
        'screenWidth': 1024,
        'sslFingerprint': {'cipherSuites': {'TLS_AES_128_GCM_SHA256': True,
                                            'TLS_AES_256_GCM_SHA384': True,
                                            'TLS_CHACHA20_POLY1305_SHA256': True,
                                            'TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA': False,
                                            'TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256': True,
                                            'TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384': True,
                                            'TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256': True,
                                            'TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA': True,
                                            'TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256': True,
                                            'TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA': True,
                                            'TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384': True,
                                            'TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256': True,
                                            'TLS_RSA_WITH_3DES_EDE_CBC_SHA': False,
                                            'TLS_RSA_WITH_AES_128_CBC_SHA': True,
                                            'TLS_RSA_WITH_AES_128_GCM_SHA256': True,
                                            'TLS_RSA_WITH_AES_256_CBC_SHA': True,
                                            'TLS_RSA_WITH_AES_256_GCM_SHA384': True},
                           'enableCustomSSL': False,
                           'versionMax': 1,
                           'versionMin': 0},
        'startUrl': 'about:blank',
        'synSettings': {'synBookmark': True,
                        'synCookie': True,
                        'synExtension': False,
                        'synHistory': True,
                        'synKeepKey': True,
                        'synLastTag': True},
        'tag': '',
        'timeZone': 'Asia/Shanghai',
        'timeZoneFillOnStart': False,
        'uaCoreFollow': False,
        'unPluginFingerprint': {'list': {'describe': [],
                                         'fileName': [],
                                         'mimeDescription': [],
                                         'mimeExtension': [],
                                         'mimeType': [],
                                         'name': []}},
        'userAgent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, '
                     'like Gecko) Chrome/91.0.4472.114 Safari/537.36',
        'webRtc': {'fillOnStart': True,
                   'lanSet': False,
                   'localIps': ['192.168.53.232'],
                   'publicIp': '125.215.109.110',
                   'type': 'BLOCK',
                   'wanSet': False},
        'webgl': {'imgProtect': True,
                  'noise': True,
                  'renderer': 'ANGLE (NVIDIA Quadro K600 Direct3D11 vs_5_0 ps_5_0)',
                  'vendor': 'ARM'}}


def save(profile, data):
    with open(f'./score/{profile}.json', 'w') as f:
        f.write(json.dumps(data, ensure_ascii=False))
    print('保存成功')


if __name__ == '__main__':
    profile = '0CBCFEBF-07F1-4340-9CE4-86CCE441A9DB'
    save(profile, data)
