# -*- coding: utf-8 -*-

# @File  : settings.py
# @Author: zibang
# @Time  : 2月 24,2022
# @Desc  :

from environs import Env

"""
获取代理
获取资源
代理减分/加分
资源减分/加分
推送log
更改TI料配置
"""
env = Env()

"""redis"""
# REDIS_HOST = env.str("REDIS_HOST", 'r-wz95j265dca7ahyov7pd.redis.rds.aliyuncs.com')  # 测试
REDIS_HOST = env.str("REDIS_HOST", 'r-wz94l16plax2n2kusdpd.redis.rds.aliyuncs.com')
# REDIS_TEST_HOST = env.str("REDIS_TEST_HOST", 'r-wz95j265dca7ahyov7pd.redis.rds.aliyuncs.com')
REDIS_PORT = env.int("REDIS_PORT", 6379)
REDIS_PASSWORD = env.str("REDIS_PASSWORD", 'lyt:GWZZPEQbvTKU1yZn2ZY7')
REDIS_TASK_KEY = 'ti_task:lyt'  # TODO 固定KEY
REDIS_PROFILE_KEY = 'lyt:profiles'
REDIS_UA_KEY = 'lyt:ua'
REDIS_LOG_KEY = 'lyt:log'
REDIS_CHANNEL = 'lyt'
REDIS_PRODUCT_KEY = 'lyt:product'
REDIS_DB = 6
"""score"""
REDIS_PROFILE_SCORE_KEY = 'score:profiles'
REDIS_PROXY_SCORE_KEY = 'score:profiles'

"""proxy"""
PROXY_COUNT = 50
PROXY_EX = 60

"""order"""
ORDER_ID = '954480323287312'

"""kdl"""
KDL_URL = 'http://dps.kdlapi.com/api/getdps/?orderid=954480323287312&num=5&signature=bfveudiqg9036cie2tzt9pt62gocv6pz&pt=1&f_loc=1&f_et=1&f_carrier=1&dedup=1&format=json&sep=1'
# KDL_URL = 'http://dps.kdlapi.com/api/getdps/?orderid=953607630812075&num=1&signature=k8laig8majr78y4s8usi0idzspvgvh7m&pt=1&f_loc=1&f_et=1&f_carrier=1&dedup=1&format=json&sep=1'

"""product url"""
PRODUCT_URL = 'https://www.ti.com.cn/store/ti/zh/p/product/?p=TIOL1123DRCR'

"""ES_HOST"""
ES_HOST = env.str("ES_HOST", 'http://127.0.0.1:9200/')

"""VMLogin"""
VM_URL = env.str("VM_URL", 'https://api.vmlogin.com/v1')
VM_TOKEN = env.str("VM_TOKEN", '068ff736efe8c0b21bb6ece6980d68ae')
# VM_TOKEN = env.str("VM_TOKEN", '155cbad18be7ab4173d1c9335881db81')
VM_LOCAL_URL = env.str("VM_LOCAL_URL", 'http://localhost:35000/api/v1')

"""Proxy"""
PROXY_USERNAME = '1139989998'
PROXY_PASSWORD = 'ntusyuox'
PROXY_POOL_COUNT = 3
PROXY_ORDER_ID = '954480323287312'

"""config"""
os = [
    "Windows",
    "Mac OS",
    "Linux",
    "iPad",
    "iPad Mini",
    "iPad Pro",
    "iPhone 4",
    "iPhone 5",
    "iPhone 5/SE",
    "iPhone SE",
    "iPhone 6",
    "iPhone 6/7/8",
    "iPhone 6 Plus",
    "iPhone 6/7/8 Plus",
    "iPhone 7",
    "iPhone 7 Plus",
    "iPhone 8",
    "iPhone 8 Plus",
    "iPhone X",
    "Laptop with touch",
    "BlackBerry Z30",
    "Blackberry PlayBook",
    "Nexus 4",
    "Nexus 5",
    "Nexus 5X",
    "Nexus 6",
    "Nexus 6P",
    "Nexus 7",
    "Nexus 10",
    "Pixel 2",
    "Pixel 2 XL",
    "Nokia N9",
    "Nokia Lumia 520",
    "Microsoft Lumia 550",
    "Microsoft Lumia 950",
    "Galaxy S5",
    "Galaxy S III",
    "Galaxy Note II",
    "Galaxy Note 3",
    "Kindle Fire HDX",
    "LG Optimus L70"
]
fontList = [
    "@Fixedsys",
    "@Malgun Gothic",
    "@Malgun Gothic Semilight",
    "@Microsoft JhengHei",
    "@Microsoft JhengHei Light",
    "@Microsoft JhengHei UI",
    "@Microsoft JhengHei UI Light",
    "@Microsoft YaHei UI",
    "@Microsoft YaHei UI Light",
    "@MingLiU_HKSCS-ExtB",
    "@MingLiU-ExtB",
    "@MS Gothic",
    "@MS PGothic",
    "@MS UI Gothic",
    "@PMingLiU-ExtB",
    "@SimSun-ExtB",
    "@System",
    "@Terminal",
    "@Yu Gothic",
    "@Yu Gothic Light",
    "@Yu Gothic Medium",
    "@Yu Gothic UI",
    "@Yu Gothic UI Light",
    "@Yu Gothic UI Semibold",
    "@Yu Gothic UI Semilight",
    "@等线",
    "@等线 Light",
    "@方正舒体",
    "@方正姚体",
    "@仿宋",
    "@黑体",
    "@华文彩云",
    "@华文仿宋",
    "@华文行楷",
    "@华文琥珀",
    "@华文楷体",
    "@华文隶书",
    "@华文宋体",
    "@华文细黑",
    "@华文新魏",
    "@华文中宋",
    "@楷体",
    "@隶书",
    "@宋体",
    "@微软雅黑",
    "@微软雅黑 Light",
    "@新宋体",
    "@幼圆",
    "Agency FB",
    "Algerian",
    "Arial",
    "Arial Black",
    "Arial Narrow",
    "Arial Rounded MT Bold",
    "Bahnschrift",
    "Bahnschrift Condensed",
    "Bahnschrift Light",
    "Bahnschrift Light Condensed",
    "Bahnschrift Light SemiCondensed",
    "Bahnschrift SemiBold",
    "Bahnschrift SemiBold Condensed",
    "Bahnschrift SemiBold SemiConden",
    "Bahnschrift SemiCondensed",
    "Bahnschrift SemiLight",
    "Bahnschrift SemiLight Condensed",
    "Bahnschrift SemiLight SemiConde",
    "Baskerville Old Face",
    "Bauhaus ",
    "Bell MT",
    "Berlin Sans FB",
    "Berlin Sans FB Demi",
    "Bernard MT Condensed",
    "Blackadder ITC",
    "Bodoni MT",
    "Bodoni MT Black",
    "Bodoni MT Condensed",
    "Bodoni MT Poster Compressed",
    "Book Antiqua",
    "Bookman Old Style",
    "Bookshelf Symbol ",
    "Bradley Hand ITC",
    "Britannic Bold",
    "Broadway",
    "Brush Script MT",
    "Calibri",
    "Calibri Light",
    "Californian FB",
    "Calisto MT",
    "Cambria",
    "Cambria Math",
    "Candara",
    "Candara Light",
    "Castellar",
    "Centaur",
    "Century",
    "Century Gothic",
    "Century Schoolbook",
    "Chiller",
    "Colonna MT",
    "Comic Sans MS",
    "Consolas",
    "Constantia",
    "Cooper Black",
    "Copperplate Gothic Bold",
    "Copperplate Gothic Light",
    "Corbel",
    "Corbel Light",
    "Courier",
    "Courier New",
    "Curlz MT",
    "Default",
    "DejaVu Sans Mono",
    "Dubai",
    "Dubai Light",
    "Dubai Medium",
    "Ebrima",
    "Edwardian Script ITC",
    "Elephant",
    "Engravers MT",
    "Eras Bold ITC",
    "Eras Demi ITC",
    "Eras Light ITC",
    "Eras Medium ITC",
    "Felix Titling",
    "Fixedsys",
    "Footlight MT Light",
    "Forte",
    "Franklin Gothic Book",
    "Franklin Gothic Demi",
    "Franklin Gothic Demi Cond",
    "Franklin Gothic Heavy",
    "Franklin Gothic Medium",
    "Franklin Gothic Medium Cond",
    "Freestyle Script",
    "French Script MT",
    "Gabriola",
    "Gadugi",
    "Garamond",
    "Georgia",
    "Gigi",
    "Gill Sans MT",
    "Gill Sans MT Condensed",
    "Gill Sans MT Ext Condensed Bold",
    "Gill Sans Ultra Bold",
    "Gill Sans Ultra Bold Condensed",
    "Gloucester MT Extra Condensed",
    "Goudy Old Style",
    "Goudy Stout",
    "Haettenschweiler",
    "Harlow Solid Italic",
    "Harrington",
    "High Tower Text",
    "HoloLens MDL Assets",
    "HP Simplified",
    "HP Simplified Light",
    "Impact",
    "Imprint MT Shadow",
    "Informal Roman",
    "Ink Free",
    "Javanese Text",
    "jdFontAwesome",
    "jdFontCustom",
    "jdIcoFont",
    "jdIcoMoonFree",
    "jdiconfontA",
    "jdiconfontB",
    "jdiconfontC",
    "jdiconfontD",
    "JdIonicons",
    "Jokerman",
    "Juice ITC",
    "Kristen ITC",
    "Kunstler Script",
    "Leelawadee UI",
    "Leelawadee UI Semilight",
    "Lucida Bright",
    "Lucida Calligraphy",
    "Lucida Console",
    "Lucida Fax",
    "Lucida Handwriting",
    "Lucida Sans",
    "Lucida Sans Typewriter",
    "Lucida Sans Unicode",
    "Magneto",
    "Maiandra GD",
    "Malgun Gothic",
    "Malgun Gothic Semilight",
    "Marlett",
    "Matura MT Script Capitals",
    "Microsoft Himalaya",
    "Microsoft JhengHei",
    "Microsoft JhengHei Light",
    "Microsoft JhengHei UI",
    "Microsoft JhengHei UI Light",
    "Microsoft New Tai Lue",
    "Microsoft PhagsPa",
    "Microsoft Sans Serif",
    "Microsoft Tai Le",
    "Microsoft YaHei UI",
    "Microsoft YaHei UI Light",
    "Microsoft Yi Baiti",
    "MingLiU_HKSCS-ExtB",
    "MingLiU-ExtB",
    "Mistral",
    "Modern",
    "Modern No. ",
    "Monaco",
    "Mongolian Baiti",
    "Monotype Corsiva",
    "MS Gothic",
    "MS Outlook",
    "MS PGothic",
    "MS Reference Sans Serif",
    "MS Reference Specialty",
    "MS Sans Serif",
    "MS Serif",
    "MS UI Gothic",
    "MT Extra",
    "MV Boli",
    "Myanmar Text",
    "Niagara Engraved",
    "Niagara Solid",
    "Nirmala UI",
    "Nirmala UI Semilight",
    "OCR A Extended",
    "Old English Text MT",
    "Onyx",
    "Palace Script MT",
    "Palatino Linotype",
    "Papyrus",
    "Parchment",
    "Perpetua",
    "Perpetua Titling MT",
    "Playbill",
    "PMingLiU-ExtB",
    "Poor Richard",
    "Pristina",
    "Rage Italic",
    "Ravie",
    "Rockwell",
    "Rockwell Condensed",
    "Rockwell Extra Bold",
    "Roman",
    "Script",
    "Script MT Bold",
    "Segoe MDL Assets",
    "Segoe Print",
    "Segoe Script",
    "Segoe UI",
    "Segoe UI Black",
    "Segoe UI Emoji",
    "Segoe UI Historic",
    "Segoe UI Light",
    "Segoe UI Semibold",
    "Segoe UI Semilight",
    "Segoe UI Symbol",
    "Showcard Gothic",
    "SimSun-ExtB",
    "Sitka Banner",
    "Sitka Display",
    "Sitka Heading",
    "Sitka Small",
    "Sitka Subheading",
    "Sitka Text",
    "Small Fonts",
    "Snap ITC",
    "Stencil",
    "Sylfaen",
    "Symbol",
    "System",
    "Tahoma",
    "Tempus Sans ITC",
    "Terminal",
    "Times New Roman",
    "Trebuchet MS",
    "Tw Cen MT",
    "Tw Cen MT Condensed",
    "Tw Cen MT Condensed Extra Bold",
    "Verdana",
    "Viner Hand ITC",
    "Vivaldi",
    "Vladimir Script",
    "Webdings",
    "Wide Latin",
    "Wingdings",
    "Wingdings ",
    "Wingdings ",
    "Yu Gothic",
    "Yu Gothic Light",
    "Yu Gothic Medium",
    "Yu Gothic UI",
    "Yu Gothic UI Light",
    "Yu Gothic UI Semibold",
    "Yu Gothic UI Semilight",
    "等线",
    "等线 Light",
    "方正舒体",
    "方正姚体",
    "仿宋",
    "黑体",
    "华文彩云",
    "华文仿宋",
    "华文行楷",
    "华文琥珀",
    "华文楷体",
    "华文隶书",
    "华文宋体",
    "华文细黑",
    "华文新魏",
    "华文中宋",
    "楷体",
    "隶书",
    "宋体",
    "微软雅黑",
    "微软雅黑 Light",
    "新宋体",
    "幼圆"
]
